Feature/df 2690 idparc sso poc
alv-ch/jobroom2 pull request #934
Opened 2020-09-11 13:07 UTC by palsch

2020-09-11 13:17 UTC, cjpsycos approved these changes

2020-09-11 13:55 UTC, birom approved these changes

2020-09-14 07:33 UTC, seco-mgabor requested changes
Please see my comments.

2020-09-14 07:33 UTC, seco-mgabor commented on jobroom-gateway-app/src/test/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOControllerTest.java
> +public class IdparcSSOControllerTest {
This is an integration test also. It should be renamed, to be able to run it in the integration test phase later on.
Usually @WebMvcTest is used to test MVC Controllers, but you should have your reasons why you did it like this. :)

2020-09-14 07:33 UTC, seco-mgabor commented on jobroom-gateway-app/src/test/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtilsTest.java
> +@SpringBootTest
Also an integration test.

2020-09-14 10:04 UTC, palsch commented on docker/gateway/central-server-config/docker-config/application.yml
> +    user:
To be consistent, I took this like it was used at other places for login-url

2020-09-14 15:35 UTC, palsch commented on jobroom-gateway-app/src/main/resources/templates/idparc-sso/autosubmit-form.html
> +    <p>
I wouldn't do that. If someone doesn't have JavaScript support, than he disabled it or uses a strange browser. So for this very specific case I wouldn't add the translation overhead.

2020-09-14 15:48 UTC, seco-mgabor commented on jobroom-gateway-app/src/main/resources/templates/idparc-sso/autosubmit-form.html
> +    <p>
If this is the case, it's OK for me too.

2020-09-15 06:39 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/config/SecurityConfiguration.java
I would rather not touch that file with my change. Maybe we could create a cleanup tech dept for this one.

2020-09-15 06:41 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/ProfileInfoResource.java
> +
I dont know, it is not my code.

2020-09-15 06:43 UTC, palsch commented on jobroom-gateway-app/src/test/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOControllerTest.java
> +public class IdparcSSOControllerTest {
All of the tests here are done in that way. So we would have to rename all of the files.
To be consistent, I used the same approach.

2020-09-15 09:25 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +    public void setNoCacheHeader(HttpServletResponse response) {
To be safe, I would like to use both, see also https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Cache-Control#Caching_verhindern

2020-09-15 09:29 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +            .filter(cookie -> cookie.getName().equals(IDPARC_SSO_JWT_COOKIE_NAME) ||
I am not sure what you mean

2020-09-15 09:32 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +            headers.setExpires(maxAge > 0 ? System.currentTimeMillis() + 1000L * maxAge : 0);
It's like ready to use date calculation. So lesser code, no need to test.

2020-09-15 09:32 UTC, palsch commented on jobroom-gateway-app/src/test/java/ch/admin/seco/jobroom/application/idparcsso/IdparcSSOServiceTest.java
> +@SpringBootTest
All of the tests here are done in that way. So we would have to rename all of the files.
To be consistent, I used the same approach.

2020-09-15 09:32 UTC, palsch commented on jobroom-gateway-app/src/test/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtilsTest.java
> +@SpringBootTest
All of the tests here are done in that way. So we would have to rename all of the files.
To be consistent, I used the same approach.

2020-09-15 09:32 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +
done

2020-09-15 09:36 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +
done

2020-09-15 09:36 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +        Context context = new Context();
done

2020-09-15 09:37 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +
done

2020-09-15 09:37 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +     */
done

2020-09-15 09:37 UTC, palsch commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOController.java
> +
done

2020-09-15 13:42 UTC, seco-mgabor commented on jobroom-gateway-app/src/test/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtilsTest.java
> +@SpringBootTest
We will rename them. This is a new test, therefore I would have preffered to be named correctly. Less work in the future...

2020-09-15 13:45 UTC, seco-mgabor commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/web/rest/idparcsso/IdparcSSOUtils.java
> +            .filter(cookie -> cookie.getName().equals(IDPARC_SSO_JWT_COOKIE_NAME) ||
Text was hidden :(

2020-09-16 14:25 UTC, seco-mgabor approved these changes

2020-09-17 11:18 UTC, merged