Feature/df 2987 improve logging for jwt saml tokens
alv-ch/jobroom2 pull request #938
Opened 2020-09-23 21:19 UTC by birom

2020-09-23 22:18 UTC, palsch approved these changes

2020-09-24 08:58 UTC, seco-mgabor requested changes

2020-09-24 08:58 UTC, seco-mgabor commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/config/WebConfigurer.java
> +
What is this filter for? Please explain it in a comment.

2020-09-24 08:58 UTC, seco-mgabor commented on jobroom-gateway-app/src/main/resources/config/bootstrap.yml
> +    pattern:
I don't understand the next line, sorry.

2020-09-24 08:58 UTC, seco-mgabor commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/infrastructure/logging/CustomMDCInsertingServletFilter.java
> +
JavaDoc is missing. What's the purpouse of this filter?

2020-09-24 08:58 UTC, seco-mgabor commented on jobroom-gateway-app/src/main/java/ch/admin/seco/jobroom/security/jwt/TokenProvider.java
> +        LOGGER.debug("Creating Token for authentication: {}", authentication);
Are you sure that ExtId, Email Address and the Session ID are visible in the log afterwards?

2020-09-24 11:01 UTC, seco-mgabor approved these changes

2020-09-24 11:33 UTC, merged